package LangAliceVerify.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Obj = 0;
  public static final int ObjRef = 1;
  public static final int ObjectRule = 2;
  public static final int RegexRule = 3;
  public static final int RentSumRule = 4;
  public static final int Rule = 5;
  public static final int RuleLists = 6;
  public static final int ValueRule = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb9a2040838d24f4bL, 0xa8f420ff93d9ed3aL);
    builder.put(0x5c9a2fcfca4336dfL, Obj);
    builder.put(0x5c9a2fcfca3fa11eL, ObjRef);
    builder.put(0x5c9a2fcfca4793e7L, ObjectRule);
    builder.put(0x5c9a2fcfca41e693L, RegexRule);
    builder.put(0x5c9a2fcfca47655cL, RentSumRule);
    builder.put(0x5c9a2fcfca3e8f00L, Rule);
    builder.put(0x5c9a2fcfca3cee28L, RuleLists);
    builder.put(0x5c9a2fcfca3e91dbL, ValueRule);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
