package LangAliceVerify.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import LangAliceVerify.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Obj:
        return new Obj_TextGen();
      case LanguageConceptSwitch.ObjRef:
        return new ObjRef_TextGen();
      case LanguageConceptSwitch.ObjectRule:
        return new ObjectRule_TextGen();
      case LanguageConceptSwitch.RegexRule:
        return new RegexRule_TextGen();
      case LanguageConceptSwitch.RentSumRule:
        return new RentSumRule_TextGen();
      case LanguageConceptSwitch.RuleLists:
        return new RuleLists_TextGen();
      case LanguageConceptSwitch.ValueRule:
        return new ValueRule_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.RuleLists$1$)) {
        String fname = getFileName_RuleLists(root);
        String ext = getFileExtension_RuleLists(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_RuleLists(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_RuleLists(SNode node) {
    return "java";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept RuleLists$1$ = MetaAdapterFactory.getConcept(0xb9a2040838d24f4bL, 0xa8f420ff93d9ed3aL, 0x5c9a2fcfca3cee28L, "LangAliceVerify.structure.RuleLists");
  }
}
