package LangAliceVerify.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class ValueRule_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("            //multiple value constraint");
    tgs.newLine();
    tgs.append("            if (!(");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.exp$is1m));
    tgs.append(")) {\n                System.out.println(\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.msg$SozU));
    tgs.append("\");\n            }");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink exp$is1m = MetaAdapterFactory.getContainmentLink(0xb9a2040838d24f4bL, 0xa8f420ff93d9ed3aL, 0x5c9a2fcfca3e91dbL, 0x5c9a2fcfca3fc6b8L, "exp");
  }

  private static final class PROPS {
    /*package*/ static final SProperty msg$SozU = MetaAdapterFactory.getProperty(0xb9a2040838d24f4bL, 0xa8f420ff93d9ed3aL, 0x5c9a2fcfca3e91dbL, 0x5c9a2fcfca430b6cL, "msg");
  }
}
