package LangAliceGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class KeyDeposit_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.newLine();
    tgs.append("\"KeyDeposit\":");
    tgs.append("{ ");
    tgs.append("\"DepositAmount\":");
    tgs.append(" \"");
    tgs.append(Integer.toString(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.Amount$o$Lo)));
    tgs.append("\", ");
    tgs.append("\"DepositPaymentDue\":");
    tgs.append(" \"");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.dueDate$jYxm));
    tgs.append("\"}");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty Amount$o$Lo = MetaAdapterFactory.getProperty(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786ca9109L, 0x2e6e221786ca92f8L, "Amount");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink dueDate$jYxm = MetaAdapterFactory.getContainmentLink(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786ca9109L, 0x2e6e221786ca9876L, "dueDate");
  }
}
