package LangAliceGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Lessor_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("{");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"FirstName\": \"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.FirstName$sijI));
    tgs.append("\", \"LastName\": \"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.LastName$VDVd));
    tgs.append("\",");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"Address\" :");
    tgs.append(" \"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.Address$Cb_L));
    tgs.append("\",");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"Emails\": [  ");
    for (SNode elem : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.emails$a7pK))) {
      tgs.append("\"");
      tgs.appendNode(elem);
      tgs.append("\"");
      if ((SNodeOperations.getNextSibling(elem) != null)) {
        tgs.append(", ");
      }
    }
    tgs.append(" ],");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"PhoneNumbers\": [ ");
    for (SNode elem_2 : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.phoneNumbers$PTpH))) {
      tgs.append("\"");
      tgs.appendNode(elem_2);
      tgs.append("\"");
      if ((SNodeOperations.getNextSibling(elem_2) != null)) {
        tgs.append(", ");
      }
    }
    tgs.append("],");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"FaxNumbers\": [ ");
    tgs.append(" ");
    for (SNode elem_3 : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.faxNumbers$VEDO))) {
      tgs.append("\"");
      tgs.appendNode(elem_3);
      tgs.append("\"");
      if ((SNodeOperations.getNextSibling(elem_3) != null)) {
        tgs.append(", ");
      }
    }
    tgs.append("]");
    tgs.newLine();
    tgs.append("}");
  }

  private static final class PROPS {
    /*package*/ static final SProperty FirstName$sijI = MetaAdapterFactory.getProperty(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c7d3d3L, 0x2e6e221786c87538L, "FirstName");
    /*package*/ static final SProperty LastName$VDVd = MetaAdapterFactory.getProperty(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c7d3d3L, 0x2e6e221786c877aaL, "LastName");
    /*package*/ static final SProperty Address$Cb_L = MetaAdapterFactory.getProperty(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c7d3d3L, 0x2e6e221786c87b55L, "Address");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink emails$a7pK = MetaAdapterFactory.getContainmentLink(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c7d3d3L, 0x2e6e221786c88418L, "emails");
    /*package*/ static final SContainmentLink phoneNumbers$PTpH = MetaAdapterFactory.getContainmentLink(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c7d3d3L, 0x2e6e221786c88dc0L, "phoneNumbers");
    /*package*/ static final SContainmentLink faxNumbers$VEDO = MetaAdapterFactory.getContainmentLink(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c7d3d3L, 0x2e6e221786c89491L, "faxNumbers");
  }
}
