package LangAliceGen.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class RentalUnit_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("{");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"Address\": ");
    tgs.append("\"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.Address$E7f4));
    tgs.append("\",");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"UnitType\": ");
    tgs.append("\"");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.unitType$2aDQ));
    tgs.append("\",");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"ApplicanceAndFurnitures\": [ ");
    for (SNode elem_6 : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.applicanceAndFurnitures$cU16))) {
      tgs.append("\"");
      tgs.appendNode(elem_6);
      tgs.append("\"");
      if ((SNodeOperations.getNextSibling(elem_6) != null)) {
        tgs.append(", ");
      }
    }
    tgs.append("],");
    tgs.newLine();
    tgs.indent();
    tgs.append("    \"Accessories\":");
    tgs.append("[ ");
    for (SNode elem_7 : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.accessories$Pz5y))) {
      tgs.append("\"");
      tgs.appendNode(elem_7);
      tgs.append("\"");
      if ((SNodeOperations.getNextSibling(elem_7) != null)) {
        tgs.append(", ");
      }
    }
    tgs.append("]");
    tgs.newLine();
    tgs.append("},");
  }

  private static final class PROPS {
    /*package*/ static final SProperty Address$E7f4 = MetaAdapterFactory.getProperty(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c8ba0dL, 0x2e6e221786c8c028L, "Address");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink unitType$2aDQ = MetaAdapterFactory.getContainmentLink(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c8ba0dL, 0x2e6e221786c8d2b5L, "unitType");
    /*package*/ static final SContainmentLink applicanceAndFurnitures$cU16 = MetaAdapterFactory.getContainmentLink(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c8ba0dL, 0x2e6e221786c8fb97L, "applicanceAndFurnitures");
    /*package*/ static final SContainmentLink accessories$Pz5y = MetaAdapterFactory.getContainmentLink(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786c8ba0dL, 0x2e6e221786c90ff1L, "accessories");
  }
}
