package LangAliceGen.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TypeLeasingPeriod extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TypeLeasingPeriod() {
    super(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786ca211aL, "TypeLeasingPeriod", "r:a3ba6696-cd38-41b3-8671-25e3fea4b5c4(LangAliceGen.structure)/3345649057623843098");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_daily_0 = new EnumerationDescriptor.MemberDescriptor("daily", "Daily", 0x2e6e221786ca233eL, "r:a3ba6696-cd38-41b3-8671-25e3fea4b5c4(LangAliceGen.structure)/3345649057623843646");
  private final EnumerationDescriptor.MemberDescriptor myMember_weekly_0 = new EnumerationDescriptor.MemberDescriptor("weekly", "Weekly", 0x2e6e221786ca23f6L, "r:a3ba6696-cd38-41b3-8671-25e3fea4b5c4(LangAliceGen.structure)/3345649057623843830");
  private final EnumerationDescriptor.MemberDescriptor myMember_biWeekly_0 = new EnumerationDescriptor.MemberDescriptor("biWeekly", "Bi-weekly", 0x2e6e221786ca25cdL, "r:a3ba6696-cd38-41b3-8671-25e3fea4b5c4(LangAliceGen.structure)/3345649057623844301");
  private final EnumerationDescriptor.MemberDescriptor myMember_monthly_0 = new EnumerationDescriptor.MemberDescriptor("monthly", "Monthly", 0x2e6e221786ca288fL, "r:a3ba6696-cd38-41b3-8671-25e3fea4b5c4(LangAliceGen.structure)/3345649057623845007");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x533d0166ce6841a9L, 0xb1ee5d3b6bc37f42L, 0x2e6e221786ca211aL, 0x2e6e221786ca233eL, 0x2e6e221786ca23f6L, 0x2e6e221786ca25cdL, 0x2e6e221786ca288fL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_daily_0, myMember_weekly_0, myMember_biWeekly_0, myMember_monthly_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_monthly_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "daily":
        return myMember_daily_0;
      case "weekly":
        return myMember_weekly_0;
      case "biWeekly":
        return myMember_biWeekly_0;
      case "monthly":
        return myMember_monthly_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
